account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [

    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),

]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path("", views.index, name="home"),
    path('index_detail/<int:id>/', views.index_detail, name='index_detail'),
]

tbal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('account/', include('account.urls')),
    path('regproje/', include('regproje.urls')),
]

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-dark my-custom-bg navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:home' %}">

            <img class="mb-" src="{% static 'assets/brand/logo4.png' %}" width="" height="27">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">

        <ul class="navbar-nav me-auto">
                <a class="nav-link" href="">Башкы бет</a>
            </li>
            <li class="nav-item dropdown">
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tema</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="">Tema 1</a></li>
                        <li><a class="dropdown-item" href="">Tema 2</a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item dropdown">
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Тема</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="">Tema 3</a></li>
                        <li><a class="dropdown-item" href="">Tema 4</a></li>
                        <li>

                    </ul>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="">Tema 5</a>
            </li>

        </ul>
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">Өздүк кабинет</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Чыгуу</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Салам, {{ user.username }} </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:login' %}">Кирүү</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:register' %}">Катталуу</a>
                </li>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

templates/partials/brand_logo.html
{% if company_info and company_info.logo %}
        <img src="{{ company_info.logo.url }}" alt="Logo" style="height: 50px;"> <!-- İstediğiniz yükseklik ve genişlik ayarını yapabilirsiniz -->
    {% endif %}
    {% if company_info and company_info.name %}
        {{ company_info.name }}
    {% else %}
        Şirket İsmi
    {% endif %}

templates/partials/print.html
 <button type="submit" class="btn btn-secondary btn-sm w-100" onclick="printTable()">Принтерге жаз</button>

templates/partials/to_exel.html
<button class="btn btn-success btn-sm" onclick="exportTableToExcel('mytable', 'report.xlsx')">Скачать в Excel</button>