main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path("", views.index, name="home"),
    path('index_detail/<int:id>/', views.index_detail, name='index_detail'),
]

regproje/urls.py
from django.urls import path
from . import views
from .views import menin_dolboorum

app_name = 'regproje'

urlpatterns = [
    path("index", views.index, name="index"),
    #path("menin_dolboorum", views.Menin_dolboorum, name="menin_dolboorum"),
    path('menin_dolboorum/', menin_dolboorum, name='menin_dolboorum'),

    path('approvers/menim-dolboorum/<int:dolboor_id>/', views.approvers_menin_dolboorum,
         name='approvers_menin_dolboorum'),
    path('confirm/', views.project_confirmation_view, name='project_confirmation'),

    path("Dolboordundudjeti", views.Dolboordundudjeti, name="Dolboordundudjeti"),
    path("Dolboordunkomandasy", views.Dolboordunkomandasy, name="Dolboordunkomandasy"),
    path("Baaloo_turuktuuluk", views.Baaloo_turuktuuluk, name="Baaloo_turuktuuluk"),
    path("Tirkemeler", views.Tirkemeler, name="Tirkemeler"),

    path('dolboor_list/', views.dolboor_list, name='dolboor_list'),
    path('create/', views.dolboor_create, name='dolboor_create'),
    path('edit/<int:pk>/', views.dolboor_edit, name='dolboor_edit'),
    path('delete/<int:pk>/', views.dolboor_delete, name='dolboor_delete'),

    path('negizgimaalymat_list/', views.negizgimaalymat_list, name='negizgimaalymat_list'),
    path('negizgimaalymat/create/', views.negizgimaalymat_create, name='negizgimaalymat_create'),
    path('negizgimaalymat/<int:pk>/edit/', views.negizgimaalymat_edit, name='negizgimaalymat_edit'),
    path('negizgimaalymat/<int:pk>/delete/', views.negizgimaalymat_delete, name='negizgimaalymat_delete'),

    path('kenenmaalymat/', views.kenenmaalymat_list, name='kenenmaalymat_list'),
    path('kenenmaalymat/create/', views.kenenmaalymat_create, name='kenenmaalymat_create'),
    path('kenenmaalymat/<int:pk>/edit/', views.kenenmaalymat_edit, name='kenenmaalymat_edit'),
    path('kenenmaalymat/<int:pk>/delete/', views.kenenmaalymat_delete, name='kenenmaalymat_delete'),

    path('iskeashyruuplany/', views.iskeashyruuplany_list, name='iskeashyruuplany_list'),
    path('iskeashyruuplany/create/', views.iskeashyruuplany_create, name='iskeashyruuplany_create'),
    path('iskeashyruuplany/<int:pk>/edit/', views.iskeashyruuplany_edit, name='iskeashyruuplany_edit'),
    path('iskeashyruuplany/<int:pk>/delete/', views.iskeashyruuplany_delete, name='iskeashyruuplany_delete'),

    path('dolboordundudjeti/', views.dolboordundudjeti_list, name='dolboordundudjeti_list'),
    path('dolboordundudjeti/create/', views.dolboordundudjeti_create, name='dolboordundudjeti_create'),
    path('dolboordundudjeti/edit/<int:pk>/', views.dolboordundudjeti_edit, name='dolboordundudjeti_edit'),
    path('dolboordundudjeti/delete/<int:pk>/', views.dolboordundudjeti_delete, name='dolboordundudjeti_delete'),

    path('dolboordunkomandasy/', views.dolboordunkomandasy_list, name='dolboordunkomandasy_list'),
    path('dolboordunkomandasy/create/', views.dolboordunkomandasy_create, name='dolboordunkomandasy_create'),
    path('dolboordunkomandasy/edit/<int:pk>/', views.dolboordunkomandasy_edit, name='dolboordunkomandasy_edit'),
    path('dolboordunkomandasy/delete/<int:pk>/', views.dolboordunkomandasy_delete, name='dolboordunkomandasy_delete'),

    path('baaloo_turuktuuluk/', views.baaloo_turuktuuluk_list, name='baaloo_turuktuuluk_list'),
    path('baaloo_turuktuuluk/create/', views.baaloo_turuktuuluk_create, name='baaloo_turuktuuluk_create'),
    path('baaloo_turuktuuluk/edit/<int:pk>/', views.baaloo_turuktuuluk_edit, name='baaloo_turuktuuluk_edit'),
    path('baaloo_turuktuuluk/delete/<int:pk>/', views.baaloo_turuktuuluk_delete, name='baaloo_turuktuuluk_delete'),

    path('tirkemeler/', views.tirkemeler_list, name='tirkemeler_list'),
    path('tirkemeler/create/', views.tirkemeler_create, name='tirkemeler_create'),
    path('tirkemeler/edit/<int:pk>/', views.tirkemeler_edit, name='tirkemeler_edit'),
    path('tirkemeler/delete/<int:pk>/', views.tirkemeler_delete, name='tirkemeler_delete'),
]

tbal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('account/', include('account.urls')),
    path('regproje/', include('regproje.urls')),
]

regproje/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import (Dolboor, Negizgimaalymat, Kenenmaalymat, Iskeashyruuplany, Project_confirmation,
                     Dolboordundudjeti, Dolboordunkomandasy, Baaloo_turuktuuluk,Tirkemeler)
from .forms import (DolboorForm, NegizgimaalymatForm, KenenmaalymatForm, TirkemelerForm,
                    IskeAshyruUplanyForm, DolboordundudjetiForm, DolboordunkomandasyForm,
                    ProjectConfirmationForm, BaalooTuruktuulukForm)
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    # Kullanıcının tüm Dolboor kayıtlarını al
    dolboors = Dolboor.objects.all()

    dolboor_data = []
    for dolboor in dolboors:
        # Kullanıcının bu dolboor için olan son onayını al
        last_confirmation = Project_confirmation.objects.filter(dolboor=dolboor, user=request.user).order_by('-created').first()
        dolboor_data.append({
            'dolboor': dolboor,
            'last_confirmation': last_confirmation,
        })

    # Template'e verileri gönder
    return render(request, "regproje/index.html", {'dolboor_data': dolboor_data})

@login_required
def approvers_menin_dolboorum(request, dolboor_id):
    dolboor = get_object_or_404(Dolboor, id=dolboor_id)
    user = dolboor.user

    user_projects = Dolboor.objects.filter(user=user)
    negizgimaalymat = Negizgimaalymat.objects.filter(user=user)
    kenenmaalymat = Kenenmaalymat.objects.filter(user=user)
    iskeashyruuplany = Iskeashyruuplany.objects.filter(user=user)
    dolboordundudjeti = Dolboordundudjeti.objects.filter(user=user)
    dolboordunkomandasy = Dolboordunkomandasy.objects.filter(user=user)
    baaloo_turuktuuluk = Baaloo_turuktuuluk.objects.filter(user=user).first()
    tirkemeler = Tirkemeler.objects.filter(user=user)

    context = {
        'dolboor': dolboor,
        'user_projects': user_projects,
        'negizgimaalymat': negizgimaalymat,
        'kenenmaalymat': kenenmaalymat,
        'iskeashyruuplany': iskeashyruuplany,
        'dolboordundudjeti': dolboordundudjeti,
        'dolboordunkomandasy': dolboordunkomandasy,
        'baaloo_turuktuuluk': baaloo_turuktuuluk,
        'tirkemeler': tirkemeler,
    }

    return render(request, "regproje/register/approvers_menin_dolboorum.html", context)



def Menin_dolboorum(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    return render(request, "regproje/register/menin_dolboorum.html")

def dolboor_list(request):
    dolboor_list = Dolboor.objects.filter(user=request.user)
    if not dolboor_list:
        return redirect('regproje:dolboor_create')
    return render(request, "regproje/register/reg-2.html", {'dolboor_list': dolboor_list})

def dolboor_create(request):
    if request.method == 'POST':
        form = DolboorForm(request.POST)
        if form.is_valid():
            dolboor = form.save(commit=False)
            dolboor.user = request.user
            dolboor.save()
            return redirect('regproje:dolboor_list')
    else:
        form = DolboorForm()
    return render(request, "regproje/register/reg-2.html", {'form': form})

def dolboor_edit(request, pk):
    dolboor = get_object_or_404(Dolboor, pk=pk)
    if request.method == 'POST':
        form = DolboorForm(request.POST, instance=dolboor)
        if form.is_valid():
            form.save()
            return redirect('regproje:dolboor_list')
    else:
        form = DolboorForm(instance=dolboor)
    return render(request, "regproje/register/reg-2.html", {'form': form, 'dolboor': dolboor})

def dolboor_delete(request, pk):
    dolboor = get_object_or_404(Dolboor, pk=pk)
    if request.method == 'POST':
        dolboor.delete()
        return redirect('regproje:dolboor_list')
    return render(request, "regproje/register/dolboor_confirm_delete.html", {'dolboor': dolboor})

# negizgimaalimat basi
def negizgimaalymat_list(request):

    negizgimaalymat_list = Negizgimaalymat.objects.filter(user=request.user)

    if not negizgimaalymat_list:  # Eğer queryset boşsa
        return redirect('regproje:negizgimaalymat_create')
    return render(request, 'regproje/register/reg-1.html', {'negizgimaalymat_list': negizgimaalymat_list})

def negizgimaalymat_create(request):
    if request.method == 'POST':
        form = NegizgimaalymatForm(request.POST)
        if form.is_valid():
            negizgimaalymat = form.save(commit=False)
            negizgimaalymat.user = request.user
            negizgimaalymat.save()
            return redirect('regproje:negizgimaalymat_list')
    else:
        form = NegizgimaalymatForm()
    return render(request, 'regproje/register/reg-1.html', {'form': form})


def negizgimaalymat_edit(request, pk):
    negizgimaalymat = get_object_or_404(Negizgimaalymat, pk=pk)
    if request.method == 'POST':
        form = NegizgimaalymatForm(request.POST, instance=negizgimaalymat)
        if form.is_valid():
            form.save()
            return redirect('regproje:negizgimaalymat_list')
    else:
        form = NegizgimaalymatForm(instance=negizgimaalymat)
    return render(request, 'regproje/register/reg-1.html', {'form': form})

def negizgimaalymat_delete(request, pk):
    negizgimaalymat = get_object_or_404(Negizgimaalymat, pk=pk)
    if request.method == 'POST':
        negizgimaalymat.delete()
        return redirect('regproje:negizgimaalymat_list')
    return render(request, 'regproje/register/negizgimaalymat_confirm_delete.html', {'negizgimaalymat': negizgimaalymat})
# negizgimaalimat buttu

def kenenmaalymat_list(request):
    kenenmaalymat_list = Kenenmaalymat.objects.filter(user=request.user)
    if not kenenmaalymat_list:
        return redirect('regproje:kenenmaalymat_create')
    return render(request, "regproje/register/kenenmaalymat.html", {'kenenmaalymat_list': kenenmaalymat_list})

def kenenmaalymat_create(request):
    if request.method == 'POST':
        form = KenenmaalymatForm(request.POST)
        if form.is_valid():
            kenenmaalymat = form.save(commit=False)
            kenenmaalymat.user = request.user
            kenenmaalymat.save()
            return redirect('regproje:kenenmaalymat_list')
    else:
        form = KenenmaalymatForm()
    return render(request, "regproje/register/kenenmaalymat.html", {'form': form})

def kenenmaalymat_edit(request, pk):
    kenenmaalymat = get_object_or_404(Kenenmaalymat, pk=pk)
    if request.method == 'POST':
        form = KenenmaalymatForm(request.POST, instance=kenenmaalymat)
        if form.is_valid():
            form.save()
            return redirect('regproje:kenenmaalymat_list')
    else:
        form = KenenmaalymatForm(instance=kenenmaalymat)
    return render(request, "regproje/register/kenenmaalymat.html", {'form': form, 'kenenmaalymat': kenenmaalymat})

def kenenmaalymat_delete(request, pk):
    kenenmaalymat = get_object_or_404(Kenenmaalymat, pk=pk)
    if request.method == 'POST':
        kenenmaalymat.delete()
        return redirect('regproje:kenenmaalymat_list')
    return render(request, "regproje/register/kenenmaalymat_confirm_delete.html", {'kenenmaalymat': kenenmaalymat})

def iskeashyruuplany_list(request):
    iskeashyruuplany_list = Iskeashyruuplany.objects.filter(user=request.user)
    if not iskeashyruuplany_list:
        return redirect('regproje:iskeashyruuplany_create')
    return render(request, "regproje/register/reg-3.html", {'iskeashyruuplany_list': iskeashyruuplany_list})

def iskeashyruuplany_create(request):
    if request.method == 'POST':
        form = IskeAshyruUplanyForm(request.POST)
        if form.is_valid():
            iskeashyruuplany = form.save(commit=False)
            iskeashyruuplany.user = request.user
            iskeashyruuplany.save()
            return redirect('regproje:iskeashyruuplany_list')
    else:
        form = IskeAshyruUplanyForm()
    return render(request, "regproje/register/reg-3.html", {'form': form})

def iskeashyruuplany_edit(request, pk):
    iskeashyruuplany = get_object_or_404(Iskeashyruuplany, pk=pk)
    if request.method == 'POST':
        form = IskeAshyruUplanyForm(request.POST, instance=iskeashyruuplany)
        if form.is_valid():
            form.save()
            return redirect('regproje:iskeashyruuplany_list')
    else:
        form = IskeAshyruUplanyForm(instance=iskeashyruuplany)
    return render(request, "regproje/register/reg-3.html", {'form': form, 'iskeashyruuplany': iskeashyruuplany})

def iskeashyruuplany_delete(request, pk):
    iskeashyruuplany = get_object_or_404(Iskeashyruuplany, pk=pk)
    if request.method == 'POST':
        iskeashyruuplany.delete()
        return redirect('regproje:iskeashyruuplany_list')
    return render(request, "regproje/register/iskeashyruuplany_confirm_delete.html", {'iskeashyruuplany': iskeashyruuplany})

def dolboordundudjeti_list(request):
    dolboordundudjeti_list = Dolboordundudjeti.objects.filter(user=request.user)
    if not dolboordundudjeti_list:
        return redirect('regproje:dolboordundudjeti_create')
    return render(request, "regproje/register/reg-4.html", {'dolboordundudjeti_list': dolboordundudjeti_list})

def dolboordundudjeti_create(request):
    if request.method == 'POST':
        form = DolboordundudjetiForm(request.POST)
        if form.is_valid():
            dolboordundudjeti = form.save(commit=False)
            dolboordundudjeti.user = request.user
            dolboordundudjeti.save()
            return redirect('regproje:dolboordundudjeti_list')
    else:
        form = DolboordundudjetiForm()
    return render(request, "regproje/register/reg-4.html", {'form': form})

def dolboordundudjeti_edit(request, pk):
    dolboordundudjeti = get_object_or_404(Dolboordundudjeti, pk=pk)
    if request.method == 'POST':
        form = DolboordundudjetiForm(request.POST, instance=dolboordundudjeti)
        if form.is_valid():

regproje/templates/regproje/register/baaloo_turuktuuluk_confirm_delete.html
{% extends "regproje/base.html" %}

{% block title %}Өчүрүү{% endblock %}

{% block content %}
<h2> Өчүрүү</h2>
<p>Бул жазууну чын эле жок кылгыңыз келеби? </p>
<p><strong>{{ dolboor.dolboordun_atalyshy }}</strong></p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Өчүрүү</button>
    <a href="{% url 'regproje:dolboor_list' %}" class="btn btn-secondary">Жокко чыгаруу</a>
</form>
{% endblock %}

regproje/templates/regproje/register/dolboor_confirm_delete.html
{% extends "regproje/base.html" %}

{% block title %}Өчүрүү{% endblock %}

{% block content %}
<h2>Долбоор Өчүрүү</h2>
<p>Бул жазууну чын эле жок кылгыңыз келеби? </p>
<p><strong>{{ dolboor.dolboordun_atalyshy }}</strong></p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Өчүрүү</button>
    <a href="{% url 'regproje:dolboor_list' %}" class="btn btn-secondary">Жокко чыгаруу</a>
</form>
{% endblock %}

regproje/templates/regproje/register/dolboordunkomandasy_confirm_delete.html
{% extends "regproje/base.html" %}

{% block title %}Өчүрүү{% endblock %}

{% block content %}
<h2> Өчүрүү</h2>
<p>Бул жазууну чын эле жок кылгыңыз келеби? </p>
<p><strong>{{ dolboor.dolboordun_atalyshy }}</strong></p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Өчүрүү</button>
    <a href="{% url 'regproje:dolboordunkomandasy_list' %}" class="btn btn-secondary">Жокко чыгаруу</a>
</form>
{% endblock %}

regproje/templates/regproje/register/kenenmaalymat.html
{% extends "regproje/base.html" %}
{% load static %}

{% block css_files %}
{% endblock %}

{% block title %} 3.Долбоор боюнча кенен маалымат  {% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="mb-0">
                3.Долбоор боюнча кенен маалымат
            </h4>
        </div>
        <div class="card-body">
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.dolboor.label }}</label>
                <div class="col-sm-8">
                    {{ form.dolboor }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.koygoi_zhana_negizdeme.label }}</label>
                <div class="col-sm-8">
                    {{ form.koygoi_zhana_negizdeme }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.maksat_zhana_mildetteri.label }}</label>
                <div class="col-sm-8">
                    {{ form.maksat_zhana_mildetteri }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label class="col-sm-4 col-form-label">{{ form.maksathtalgan_auditoriya.label }}</label>
                <div class="col-sm-8">
                    {{ form.maksathtalgan_auditoriya }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label class="col-sm-4 col-form-label">{{ form.kutulgozh_zhyintyk.label }}</label>
                <div class="col-sm-8">
                    {{ form.kutulgozh_zhyintyk }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label class="col-sm-4 col-form-label">{{ form.tobokelchilikter.label }}</label>
                <div class="col-sm-8">
                    {{ form.tobokelchilikter }}
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Сактоо</button>

</form>
{% if kenenmaalymat_list %}
    <h3>Долбоор боюнча кенен маалымат</h3>
    <ul>
        {% for kenenmaalymat in kenenmaalymat_list %}
        <li>
            {{ kenenmaalymat.koygoi_zhana_negizdeme }} -
            <a href="{% url 'regproje:kenenmaalymat_edit' kenenmaalymat.pk %}">Өзгөртүү</a> |
            <a href="{% url 'regproje:kenenmaalymat_delete' kenenmaalymat.pk %}">Өчүрүү</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Азырынча эч кандай Кенен маалымат катталган эмес. <a href="{% url 'regproje:kenenmaalymat_create' %}">Жаңы Кенен маалымат түзүңүз.</a></p>
{% endif %}{% endblock %}

regproje/templates/regproje/register/reg-1.html
{% extends "regproje/base.html" %}
{% load static %}

{% block css_files %}
{% endblock %}

{% block title %} Negizgimaalymat Formu {% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="mb-0">2.Негизги маалымат</h4>
        </div>
        <div class="card-body">
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.dolboor.label }}</label>
                <div class="col-sm-8">
                    {{ form.dolboor }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label class="col-sm-4 col-form-label">{{ form.yuridikalyk_jekekishi.label }}</label>
                <div class="col-sm-8">
                    {{ form.yuridikalyk_jekekishi }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.aty_jonu.label }}</label>
                <div class="col-sm-8">
                    {{ form.aty_jonu }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.mekmenin_atalyshy.label }}</label>
                <div class="col-sm-8">
                    {{ form.mekmenin_atalyshy }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.mekmenin_zhetekchisi.label }}</label>
                <div class="col-sm-8">
                    {{ form.mekmenin_zhetekchisi }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.pozitsiyasi.label }}</label>
                <div class="col-sm-8">
                    {{ form.pozitsiyasi }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.baylanysh_telefonu.label }}</label>
                <div class="col-sm-8">
                    {{ form.baylanysh_telefonu }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label class="col-sm-4 col-form-label">{{ form.mobildik_telefonu.label }}</label>
                <div class="col-sm-8">
                    {{ form.mobildik_telefonu }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label  class="col-sm-4 col-form-label">{{ form.email.label }}</label>
                <div class="col-sm-8">
                    {{ form.email }}
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Сактоо</button>
</form>

{% if negizgimaalymat_list %}
    <h3>Сакталган маалыматтар тизмеси</h3>
    <ul>
        {% for item in negizgimaalymat_list %}
        <li>
            {{ item.aty_jonu }} -
            <a href="{% url 'regproje:negizgimaalymat_edit' item.pk %}">Өзгөртүү</a> |
            <a href="{% url 'regproje:negizgimaalymat_delete' item.pk %}">Өчүрүү</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Азырынча эч кандай маалымат жок. <a href="{% url 'regproje:negizgimaalymat_create' %}">Жаңы маалымат түзүңүз.</a></p>
{% endif %}

{% endblock %}

regproje/templates/regproje/register/reg-5.html
{% extends "regproje/base.html" %}
{% load static %}

{% block css_files %}
{% endblock %}

{% block title %} Команда Формасы {% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="mb-0">6.	Долбоордун командасы</h4>
        </div>
        <div class="card-body">
            <div class="form-group row mt-2">
                <label for="{{ form.dolboor.id_for_label }}" class="col-sm-4 col-form-label">{{ form.dolboor.label }}</label>
                <div class="col-sm-8">
                    {{ form.dolboor }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label for="{{ form.negizgi_katyshuuchular.id_for_label }}" class="col-sm-4 col-form-label">{{ form.negizgi_katyshuuchular.label }}</label>
                <div class="col-sm-8">
                    {{ form.negizgi_katyshuuchular }}
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Сактоо</button>
</form>

{% if dolboordunkomandasy_list %}
    <h3>Долбоордун командасы жөнүндө сакталган маалымат</h3>
    <ul>
        {% for komanda in dolboordunkomandasy_list %}
        <li>
            {{ komanda.negizgi_katyshuuchular }} -
            <a href="{% url 'regproje:dolboordunkomandasy_edit' komanda.pk %}">Өзгөртүү</a> |
            <a href="{% url 'regproje:dolboordunkomandasy_delete' komanda.pk %}">Өчүрүү</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Азырынча эч кандай Команда катталган эмес. <a href="{% url 'regproje:dolboordunkomandasy_create' %}">Жаңы Команда түзүңүз.</a></p>
{% endif %}

{% endblock %}

regproje/templates/regproje/register/reg-6.html
{% extends "regproje/base.html" %}
{% load static %}

{% block css_files %}
{% endblock %}

{% block title %} Баалоо Туруктуулук Формасы {% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="mb-0">7.	Баалоо жана туруктуулук</h4>
        </div>
        <div class="card-body">
            <div class="form-group row mt-2">
                <label for="{{ form.dolboor.id_for_label }}" class="col-sm-4 col-form-label">{{ form.dolboor.label }}</label>
                <div class="col-sm-8">
                    {{ form.dolboor }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label for="{{ form.baaloo_metoddoru.id_for_label }}" class="col-sm-4 col-form-label">{{ form.baaloo_metoddoru.label }}</label>
                <div class="col-sm-8">
                    {{ form.baaloo_metoddoru }}
                </div>
            </div>
            <div class="form-group row mt-2">
                <label for="{{ form.turuktuluk_plany.id_for_label }}" class="col-sm-4 col-form-label">{{ form.turuktuluk_plany.label }}</label>
                <div class="col-sm-8">
                    {{ form.turuktuluk_plany }}
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Сактоо</button>
</form>

{% if baaloo_turuktuuluk_list %}
    <h3>Баалоо жана туруктуулук жөнүндө маалымат</h3>
    <ul>
        {% for item in baaloo_turuktuuluk_list %}
        <li>
            {{ item.baaloo_metoddoru|slice:":30" }} -
            <a href="{% url 'regproje:baaloo_turuktuuluk_edit' item.pk %}">Өзгөртүү</a> |
            <a href="{% url 'regproje:baaloo_turuktuuluk_delete' item.pk %}">Өчүрүү</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Азырынча эч кандай Баалоо жана туруктуулук катталган эмес. <a href="{% url 'regproje:baaloo_turuktuuluk_create' %}">Жаңы Баалоо жана туруктуулук түзүңүз.</a></p>
{% endif %}

{% endblock %}