account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [

    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),

]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path("", views.index, name="home"),
    path('index_detail/<int:id>/', views.index_detail, name='index_detail'),
]

regproje/urls.py
from django.urls import path
from . import views
from .views import menin_dolboorum

app_name = 'regproje'

urlpatterns = [
    path("index", views.index, name="index"),
    #path("menin_dolboorum", views.Menin_dolboorum, name="menin_dolboorum"),
    path('menin_dolboorum/', menin_dolboorum, name='menin_dolboorum'),

    path('approvers/menim-dolboorum/<int:dolboor_id>/', views.approvers_menin_dolboorum,
         name='approvers_menin_dolboorum'),
    path('confirm/', views.project_confirmation_view, name='project_confirmation'),

    path("Dolboordundudjeti", views.Dolboordundudjeti, name="Dolboordundudjeti"),
    path("Dolboordunkomandasy", views.Dolboordunkomandasy, name="Dolboordunkomandasy"),
    path("Baaloo_turuktuuluk", views.Baaloo_turuktuuluk, name="Baaloo_turuktuuluk"),
    path("Tirkemeler", views.Tirkemeler, name="Tirkemeler"),

    path('dolboor_list/', views.dolboor_list, name='dolboor_list'),
    path('create/', views.dolboor_create, name='dolboor_create'),
    path('edit/<int:pk>/', views.dolboor_edit, name='dolboor_edit'),
    path('delete/<int:pk>/', views.dolboor_delete, name='dolboor_delete'),

    path('negizgimaalymat_list/', views.negizgimaalymat_list, name='negizgimaalymat_list'),
    path('negizgimaalymat/create/', views.negizgimaalymat_create, name='negizgimaalymat_create'),
    path('negizgimaalymat/<int:pk>/edit/', views.negizgimaalymat_edit, name='negizgimaalymat_edit'),
    path('negizgimaalymat/<int:pk>/delete/', views.negizgimaalymat_delete, name='negizgimaalymat_delete'),

    path('kenenmaalymat/', views.kenenmaalymat_list, name='kenenmaalymat_list'),
    path('kenenmaalymat/create/', views.kenenmaalymat_create, name='kenenmaalymat_create'),
    path('kenenmaalymat/<int:pk>/edit/', views.kenenmaalymat_edit, name='kenenmaalymat_edit'),
    path('kenenmaalymat/<int:pk>/delete/', views.kenenmaalymat_delete, name='kenenmaalymat_delete'),

    path('iskeashyruuplany/', views.iskeashyruuplany_list, name='iskeashyruuplany_list'),
    path('iskeashyruuplany/create/', views.iskeashyruuplany_create, name='iskeashyruuplany_create'),
    path('iskeashyruuplany/<int:pk>/edit/', views.iskeashyruuplany_edit, name='iskeashyruuplany_edit'),
    path('iskeashyruuplany/<int:pk>/delete/', views.iskeashyruuplany_delete, name='iskeashyruuplany_delete'),

    path('dolboordundudjeti/', views.dolboordundudjeti_list, name='dolboordundudjeti_list'),
    path('dolboordundudjeti/create/', views.dolboordundudjeti_create, name='dolboordundudjeti_create'),
    path('dolboordundudjeti/edit/<int:pk>/', views.dolboordundudjeti_edit, name='dolboordundudjeti_edit'),
    path('dolboordundudjeti/delete/<int:pk>/', views.dolboordundudjeti_delete, name='dolboordundudjeti_delete'),

    path('dolboordunkomandasy/', views.dolboordunkomandasy_list, name='dolboordunkomandasy_list'),
    path('dolboordunkomandasy/create/', views.dolboordunkomandasy_create, name='dolboordunkomandasy_create'),
    path('dolboordunkomandasy/edit/<int:pk>/', views.dolboordunkomandasy_edit, name='dolboordunkomandasy_edit'),
    path('dolboordunkomandasy/delete/<int:pk>/', views.dolboordunkomandasy_delete, name='dolboordunkomandasy_delete'),

    path('baaloo_turuktuuluk/', views.baaloo_turuktuuluk_list, name='baaloo_turuktuuluk_list'),
    path('baaloo_turuktuuluk/create/', views.baaloo_turuktuuluk_create, name='baaloo_turuktuuluk_create'),
    path('baaloo_turuktuuluk/edit/<int:pk>/', views.baaloo_turuktuuluk_edit, name='baaloo_turuktuuluk_edit'),
    path('baaloo_turuktuuluk/delete/<int:pk>/', views.baaloo_turuktuuluk_delete, name='baaloo_turuktuuluk_delete'),

    path('tirkemeler/', views.tirkemeler_list, name='tirkemeler_list'),
    path('tirkemeler/create/', views.tirkemeler_create, name='tirkemeler_create'),
    path('tirkemeler/edit/<int:pk>/', views.tirkemeler_edit, name='tirkemeler_edit'),
    path('tirkemeler/delete/<int:pk>/', views.tirkemeler_delete, name='tirkemeler_delete'),
]

tbal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('account/', include('account.urls')),
    path('regproje/', include('regproje.urls')),
]

regproje/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import (Dolboor, Negizgimaalymat, Kenenmaalymat, Iskeashyruuplany, Project_confirmation,
                     Dolboordundudjeti, Dolboordunkomandasy, Baaloo_turuktuuluk,Tirkemeler)
from .forms import (DolboorForm, NegizgimaalymatForm, KenenmaalymatForm, TirkemelerForm,
                    IskeAshyruUplanyForm, DolboordundudjetiForm, DolboordunkomandasyForm,
                    ProjectConfirmationForm, BaalooTuruktuulukForm)
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    # Kullanıcının tüm Dolboor kayıtlarını al
    dolboors = Dolboor.objects.all()

    dolboor_data = []
    for dolboor in dolboors:
        # Kullanıcının bu dolboor için olan son onayını al
        last_confirmation = Project_confirmation.objects.filter(dolboor=dolboor, user=request.user).order_by('-created').first()
        dolboor_data.append({
            'dolboor': dolboor,
            'last_confirmation': last_confirmation,
        })

    # Template'e verileri gönder
    return render(request, "regproje/index.html", {'dolboor_data': dolboor_data})

@login_required
def approvers_menin_dolboorum(request, dolboor_id):
    dolboor = get_object_or_404(Dolboor, id=dolboor_id)
    user = dolboor.user

    user_projects = Dolboor.objects.filter(user=user)
    negizgimaalymat = Negizgimaalymat.objects.filter(user=user)
    kenenmaalymat = Kenenmaalymat.objects.filter(user=user)
    iskeashyruuplany = Iskeashyruuplany.objects.filter(user=user)
    dolboordundudjeti = Dolboordundudjeti.objects.filter(user=user)
    dolboordunkomandasy = Dolboordunkomandasy.objects.filter(user=user)
    baaloo_turuktuuluk = Baaloo_turuktuuluk.objects.filter(user=user).first()
    tirkemeler = Tirkemeler.objects.filter(user=user)

    context = {
        'dolboor': dolboor,
        'user_projects': user_projects,
        'negizgimaalymat': negizgimaalymat,
        'kenenmaalymat': kenenmaalymat,
        'iskeashyruuplany': iskeashyruuplany,
        'dolboordundudjeti': dolboordundudjeti,
        'dolboordunkomandasy': dolboordunkomandasy,
        'baaloo_turuktuuluk': baaloo_turuktuuluk,
        'tirkemeler': tirkemeler,
    }

    return render(request, "regproje/register/approvers_menin_dolboorum.html", context)



def Menin_dolboorum(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    return render(request, "regproje/register/menin_dolboorum.html")

def dolboor_list(request):
    dolboor_list = Dolboor.objects.filter(user=request.user)
    if not dolboor_list:
        return redirect('regproje:dolboor_create')
    return render(request, "regproje/register/reg-2.html", {'dolboor_list': dolboor_list})

def dolboor_create(request):
    if request.method == 'POST':
        form = DolboorForm(request.POST)
        if form.is_valid():
            dolboor = form.save(commit=False)
            dolboor.user = request.user
            dolboor.save()
            return redirect('regproje:dolboor_list')
    else:
        form = DolboorForm()
    return render(request, "regproje/register/reg-2.html", {'form': form})

def dolboor_edit(request, pk):
    dolboor = get_object_or_404(Dolboor, pk=pk)
    if request.method == 'POST':
        form = DolboorForm(request.POST, instance=dolboor)
        if form.is_valid():
            form.save()
            return redirect('regproje:dolboor_list')
    else:
        form = DolboorForm(instance=dolboor)
    return render(request, "regproje/register/reg-2.html", {'form': form, 'dolboor': dolboor})

def dolboor_delete(request, pk):
    dolboor = get_object_or_404(Dolboor, pk=pk)
    if request.method == 'POST':
        dolboor.delete()
        return redirect('regproje:dolboor_list')
    return render(request, "regproje/register/dolboor_confirm_delete.html", {'dolboor': dolboor})

# negizgimaalimat basi
def negizgimaalymat_list(request):

    negizgimaalymat_list = Negizgimaalymat.objects.filter(user=request.user)

    if not negizgimaalymat_list:  # Eğer queryset boşsa
        return redirect('regproje:negizgimaalymat_create')
    return render(request, 'regproje/register/reg-1.html', {'negizgimaalymat_list': negizgimaalymat_list})

def negizgimaalymat_create(request):
    if request.method == 'POST':
        form = NegizgimaalymatForm(request.POST)
        if form.is_valid():
            negizgimaalymat = form.save(commit=False)
            negizgimaalymat.user = request.user
            negizgimaalymat.save()
            return redirect('regproje:negizgimaalymat_list')
    else:
        form = NegizgimaalymatForm()
    return render(request, 'regproje/register/reg-1.html', {'form': form})


def negizgimaalymat_edit(request, pk):
    negizgimaalymat = get_object_or_404(Negizgimaalymat, pk=pk)
    if request.method == 'POST':
        form = NegizgimaalymatForm(request.POST, instance=negizgimaalymat)
        if form.is_valid():
            form.save()
            return redirect('regproje:negizgimaalymat_list')
    else:
        form = NegizgimaalymatForm(instance=negizgimaalymat)
    return render(request, 'regproje/register/reg-1.html', {'form': form})

def negizgimaalymat_delete(request, pk):
    negizgimaalymat = get_object_or_404(Negizgimaalymat, pk=pk)
    if request.method == 'POST':
        negizgimaalymat.delete()
        return redirect('regproje:negizgimaalymat_list')
    return render(request, 'regproje/register/negizgimaalymat_confirm_delete.html', {'negizgimaalymat': negizgimaalymat})
# negizgimaalimat buttu

def kenenmaalymat_list(request):
    kenenmaalymat_list = Kenenmaalymat.objects.filter(user=request.user)
    if not kenenmaalymat_list:
        return redirect('regproje:kenenmaalymat_create')
    return render(request, "regproje/register/kenenmaalymat.html", {'kenenmaalymat_list': kenenmaalymat_list})

def kenenmaalymat_create(request):
    if request.method == 'POST':
        form = KenenmaalymatForm(request.POST)
        if form.is_valid():
            kenenmaalymat = form.save(commit=False)
            kenenmaalymat.user = request.user
            kenenmaalymat.save()
            return redirect('regproje:kenenmaalymat_list')
    else:
        form = KenenmaalymatForm()
    return render(request, "regproje/register/kenenmaalymat.html", {'form': form})

def kenenmaalymat_edit(request, pk):
    kenenmaalymat = get_object_or_404(Kenenmaalymat, pk=pk)
    if request.method == 'POST':
        form = KenenmaalymatForm(request.POST, instance=kenenmaalymat)
        if form.is_valid():
            form.save()
            return redirect('regproje:kenenmaalymat_list')
    else:
        form = KenenmaalymatForm(instance=kenenmaalymat)
    return render(request, "regproje/register/kenenmaalymat.html", {'form': form, 'kenenmaalymat': kenenmaalymat})

def kenenmaalymat_delete(request, pk):
    kenenmaalymat = get_object_or_404(Kenenmaalymat, pk=pk)
    if request.method == 'POST':
        kenenmaalymat.delete()
        return redirect('regproje:kenenmaalymat_list')
    return render(request, "regproje/register/kenenmaalymat_confirm_delete.html", {'kenenmaalymat': kenenmaalymat})

def iskeashyruuplany_list(request):
    iskeashyruuplany_list = Iskeashyruuplany.objects.filter(user=request.user)
    if not iskeashyruuplany_list:
        return redirect('regproje:iskeashyruuplany_create')
    return render(request, "regproje/register/reg-3.html", {'iskeashyruuplany_list': iskeashyruuplany_list})

def iskeashyruuplany_create(request):
    if request.method == 'POST':
        form = IskeAshyruUplanyForm(request.POST)
        if form.is_valid():
            iskeashyruuplany = form.save(commit=False)
            iskeashyruuplany.user = request.user
            iskeashyruuplany.save()
            return redirect('regproje:iskeashyruuplany_list')
    else:
        form = IskeAshyruUplanyForm()
    return render(request, "regproje/register/reg-3.html", {'form': form})

def iskeashyruuplany_edit(request, pk):
    iskeashyruuplany = get_object_or_404(Iskeashyruuplany, pk=pk)
    if request.method == 'POST':
        form = IskeAshyruUplanyForm(request.POST, instance=iskeashyruuplany)
        if form.is_valid():
            form.save()
            return redirect('regproje:iskeashyruuplany_list')
    else:
        form = IskeAshyruUplanyForm(instance=iskeashyruuplany)
    return render(request, "regproje/register/reg-3.html", {'form': form, 'iskeashyruuplany': iskeashyruuplany})

def iskeashyruuplany_delete(request, pk):
    iskeashyruuplany = get_object_or_404(Iskeashyruuplany, pk=pk)
    if request.method == 'POST':
        iskeashyruuplany.delete()
        return redirect('regproje:iskeashyruuplany_list')
    return render(request, "regproje/register/iskeashyruuplany_confirm_delete.html", {'iskeashyruuplany': iskeashyruuplany})

def dolboordundudjeti_list(request):
    dolboordundudjeti_list = Dolboordundudjeti.objects.filter(user=request.user)
    if not dolboordundudjeti_list:
        return redirect('regproje:dolboordundudjeti_create')
    return render(request, "regproje/register/reg-4.html", {'dolboordundudjeti_list': dolboordundudjeti_list})

def dolboordundudjeti_create(request):
    if request.method == 'POST':
        form = DolboordundudjetiForm(request.POST)
        if form.is_valid():
            dolboordundudjeti = form.save(commit=False)
            dolboordundudjeti.user = request.user
            dolboordundudjeti.save()
            return redirect('regproje:dolboordundudjeti_list')
    else:
        form = DolboordundudjetiForm()
    return render(request, "regproje/register/reg-4.html", {'form': form})

def dolboordundudjeti_edit(request, pk):
    dolboordundudjeti = get_object_or_404(Dolboordundudjeti, pk=pk)
    if request.method == 'POST':
        form = DolboordundudjetiForm(request.POST, instance=dolboordundudjeti)
        if form.is_valid():

regproje/templates/regproje/base.html
<!doctype html>
{% load static %}
{% block extrahead %}
    {{ block.super }}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/brand/favicon.ico' %}">
{% endblock %}
<html lang="en" data-bs-theme="auto">
<head>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="{% static 'assets/js/color-modes.js' %}"></script>
<link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBogGzU1OgkYFZilHafgg+GYnTn0gjN15SbWkdZ3QKkR4NX9" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'reports/css/index_style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
<link href="{% static 'main/css/dashboard.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/brand/favicon.ico' %}">
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Toobaldary</title>
   {% block css_files %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>
  <body>
    {% include 'main/partials/_svg.html' %}

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow my-custom-bg" >
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="{% url 'main:home' %}">
      <img class="mb-" src="{% static 'assets/brand/logo5.png' %}" alt="" width="" height="45"></a>
  <ul class="navbar-nav flex-row d-md-none">
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle search">
        <i class="bi bi-search"></i>
      </button>
    </li>
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <i class="bi bi-list"></i>
      </button>
    </li>
  </ul>
  <div id="navbarSearch" class="navbar-search w-100 collapse">
    <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  </div>
</header>
<div class="container-fluid">
  <div class="row">
    <!--sidebar--------------->
      <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
      <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="sidebarMenuLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
<!--menu2 -->
          {% include 'regproje/partials/_menu_users.html' %}
<!---menu3 -->
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase ">
            <span>Өздүк маалыматтар</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
              <i class="bi bi-plus-circle"></i>
            </a>
          </h6>
          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="">
                <i class="bi bi-file-earmark-text"></i>
                Маалымат 1
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-file-earmark-text"></i>
                Маалымат 2
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-file-earmark-text"></i>
                Маалымат 3
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <i class="bi bi-file-earmark-text"></i>
                Маалымат 4
              </a>
            </li>
          </ul>

          <hr class="my-3">

          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="/admin/">
                <i class="bi bi-gear-wide-connected"></i>
                Орнотуулар
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{%url 'account:logout'%}">
                <i class="bi bi-door-closed"></i>
                Чыгуу
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
      <!---sidebar------------->
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h4">Билим берүү боюнча долбоорго кайрылуу формасы</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">

          </div>

           <div class="d-flex ms-auto">
    {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'account:logout' %}">Чыгуу - </a>
           <a class="nav-link" href=""> - Саламатсызбы {{ user.username }} </a>
           {% else %}
            <a class="nav-link" href="{% url 'account:login' %}">Вход  </a>
    {% endif %}
           </div>

        </div>
      </div>
      {% block content %}{% endblock %}

    </main>
  </div>
</div>
    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js" integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp" crossorigin="anonymous"></script>
    <script src="{% static 'main/js/dashboard.js' %}"></script>
  </body>
</html>

regproje/templates/regproje/index.html
{% extends "regproje/base_approvers.html" %}
{% load static %}
{% block css_files %}
{% endblock %}

{% block title %}Комиссия мүчөсү баракчасы{% endblock %}

{% block content %}
<div class="container mt-2">

    <h4>Долбоорлор</h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Долбоордун ээси</th>
                <th>Долбоордун аталышы</th>
                <th>Коментарий</th>
                <th>Кыймыл</th>
            </tr>
        </thead>
        <tbody>
            {% for item in dolboor_data %}
            <tr>
                <td>
                    {{ item.dolboor.user. }} {{ item.dolboor.user.last_name }}
                </td>
                <td><a href="{% url 'regproje:approvers_menin_dolboorum' item.dolboor.id %}">{{ item.dolboor.dolboordun_atalyshy }}</a></td>
                <td>
                    {% if item.last_confirmation %}
                        {{ item.last_confirmation.comment }}
                    {% else %}
                        <span style="color: ;">Комментарий жок</span>
                    {% endif %}
                </td>
                <td>
                    {% if item.last_confirmation and item.last_confirmation.confirmation %}
                        <span style="color: green;"><strong>Макулдашылды</strong></span>
                    {% else %}
                    <form method="post" action="{% url 'regproje:project_confirmation' %}">
                        {% csrf_token %}
                        <input type="hidden" name="dolboor_id" value="{{ item.dolboor.id }}">
                        <input type="text" name="comment" >
                        <input type="checkbox" id="approval_{{ item.dolboor.id }}" name="confirmation">
                        <label for="approval_{{ item.dolboor.id }}">Макулмун</label>
                        <input type="hidden" name="applicant_user_id" value="{{ item.dolboor.user_id }}">{{ item.dolboor.user_id }}
                        <button type="submit" class="btn btn-sm btn-secondary ms-4">Жөнөт</button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}