main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path("", views.index, name="home"),
    path('index_detail/<int:id>/', views.index_detail, name='index_detail'),
]

regproje/urls.py
from django.urls import path
from . import views
from .views import menin_dolboorum

app_name = 'regproje'

urlpatterns = [
    path("index", views.index, name="index"),
    #path("menin_dolboorum", views.Menin_dolboorum, name="menin_dolboorum"),
    path('menin_dolboorum/', menin_dolboorum, name='menin_dolboorum'),

    path('approvers/menim-dolboorum/<int:dolboor_id>/', views.approvers_menin_dolboorum,
         name='approvers_menin_dolboorum'),
    path('confirm/', views.project_confirmation_view, name='project_confirmation'),

    path("Dolboordundudjeti", views.Dolboordundudjeti, name="Dolboordundudjeti"),
    path("Dolboordunkomandasy", views.Dolboordunkomandasy, name="Dolboordunkomandasy"),
    path("Baaloo_turuktuuluk", views.Baaloo_turuktuuluk, name="Baaloo_turuktuuluk"),
    path("Tirkemeler", views.Tirkemeler, name="Tirkemeler"),

    path('dolboor_list/', views.dolboor_list, name='dolboor_list'),
    path('create/', views.dolboor_create, name='dolboor_create'),
    path('edit/<int:pk>/', views.dolboor_edit, name='dolboor_edit'),
    path('delete/<int:pk>/', views.dolboor_delete, name='dolboor_delete'),

    path('negizgimaalymat_list/', views.negizgimaalymat_list, name='negizgimaalymat_list'),
    path('negizgimaalymat/create/', views.negizgimaalymat_create, name='negizgimaalymat_create'),
    path('negizgimaalymat/<int:pk>/edit/', views.negizgimaalymat_edit, name='negizgimaalymat_edit'),
    path('negizgimaalymat/<int:pk>/delete/', views.negizgimaalymat_delete, name='negizgimaalymat_delete'),

    path('kenenmaalymat/', views.kenenmaalymat_list, name='kenenmaalymat_list'),
    path('kenenmaalymat/create/', views.kenenmaalymat_create, name='kenenmaalymat_create'),
    path('kenenmaalymat/<int:pk>/edit/', views.kenenmaalymat_edit, name='kenenmaalymat_edit'),
    path('kenenmaalymat/<int:pk>/delete/', views.kenenmaalymat_delete, name='kenenmaalymat_delete'),

    path('iskeashyruuplany/', views.iskeashyruuplany_list, name='iskeashyruuplany_list'),
    path('iskeashyruuplany/create/', views.iskeashyruuplany_create, name='iskeashyruuplany_create'),
    path('iskeashyruuplany/<int:pk>/edit/', views.iskeashyruuplany_edit, name='iskeashyruuplany_edit'),
    path('iskeashyruuplany/<int:pk>/delete/', views.iskeashyruuplany_delete, name='iskeashyruuplany_delete'),

    path('dolboordundudjeti/', views.dolboordundudjeti_list, name='dolboordundudjeti_list'),
    path('dolboordundudjeti/create/', views.dolboordundudjeti_create, name='dolboordundudjeti_create'),
    path('dolboordundudjeti/edit/<int:pk>/', views.dolboordundudjeti_edit, name='dolboordundudjeti_edit'),
    path('dolboordundudjeti/delete/<int:pk>/', views.dolboordundudjeti_delete, name='dolboordundudjeti_delete'),

    path('dolboordunkomandasy/', views.dolboordunkomandasy_list, name='dolboordunkomandasy_list'),
    path('dolboordunkomandasy/create/', views.dolboordunkomandasy_create, name='dolboordunkomandasy_create'),
    path('dolboordunkomandasy/edit/<int:pk>/', views.dolboordunkomandasy_edit, name='dolboordunkomandasy_edit'),
    path('dolboordunkomandasy/delete/<int:pk>/', views.dolboordunkomandasy_delete, name='dolboordunkomandasy_delete'),

    path('baaloo_turuktuuluk/', views.baaloo_turuktuuluk_list, name='baaloo_turuktuuluk_list'),
    path('baaloo_turuktuuluk/create/', views.baaloo_turuktuuluk_create, name='baaloo_turuktuuluk_create'),
    path('baaloo_turuktuuluk/edit/<int:pk>/', views.baaloo_turuktuuluk_edit, name='baaloo_turuktuuluk_edit'),
    path('baaloo_turuktuuluk/delete/<int:pk>/', views.baaloo_turuktuuluk_delete, name='baaloo_turuktuuluk_delete'),

    path('tirkemeler/', views.tirkemeler_list, name='tirkemeler_list'),
    path('tirkemeler/create/', views.tirkemeler_create, name='tirkemeler_create'),
    path('tirkemeler/edit/<int:pk>/', views.tirkemeler_edit, name='tirkemeler_edit'),
    path('tirkemeler/delete/<int:pk>/', views.tirkemeler_delete, name='tirkemeler_delete'),
]

tbal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('account/', include('account.urls')),
    path('regproje/', include('regproje.urls')),
]

regproje/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import (Dolboor, Negizgimaalymat, Kenenmaalymat, Iskeashyruuplany, Project_confirmation,
                     Dolboordundudjeti, Dolboordunkomandasy, Baaloo_turuktuuluk,Tirkemeler)
from .forms import (DolboorForm, NegizgimaalymatForm, KenenmaalymatForm, TirkemelerForm,
                    IskeAshyruUplanyForm, DolboordundudjetiForm, DolboordunkomandasyForm,
                    ProjectConfirmationForm, BaalooTuruktuulukForm)
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    # Kullanıcının tüm Dolboor kayıtlarını al
    dolboors = Dolboor.objects.all()

    dolboor_data = []
    for dolboor in dolboors:
        # Kullanıcının bu dolboor için olan son onayını al
        last_confirmation = Project_confirmation.objects.filter(dolboor=dolboor, user=request.user).order_by('-created').first()
        dolboor_data.append({
            'dolboor': dolboor,
            'last_confirmation': last_confirmation,
        })

    # Template'e verileri gönder
    return render(request, "regproje/index.html", {'dolboor_data': dolboor_data})

@login_required
def approvers_menin_dolboorum(request, dolboor_id):
    dolboor = get_object_or_404(Dolboor, id=dolboor_id)
    user = dolboor.user

    user_projects = Dolboor.objects.filter(user=user)
    negizgimaalymat = Negizgimaalymat.objects.filter(user=user)
    kenenmaalymat = Kenenmaalymat.objects.filter(user=user)
    iskeashyruuplany = Iskeashyruuplany.objects.filter(user=user)
    dolboordundudjeti = Dolboordundudjeti.objects.filter(user=user)
    dolboordunkomandasy = Dolboordunkomandasy.objects.filter(user=user)
    baaloo_turuktuuluk = Baaloo_turuktuuluk.objects.filter(user=user).first()
    tirkemeler = Tirkemeler.objects.filter(user=user)

    context = {
        'dolboor': dolboor,
        'user_projects': user_projects,
        'negizgimaalymat': negizgimaalymat,
        'kenenmaalymat': kenenmaalymat,
        'iskeashyruuplany': iskeashyruuplany,
        'dolboordundudjeti': dolboordundudjeti,
        'dolboordunkomandasy': dolboordunkomandasy,
        'baaloo_turuktuuluk': baaloo_turuktuuluk,
        'tirkemeler': tirkemeler,
    }

    return render(request, "regproje/register/approvers_menin_dolboorum.html", context)



def Menin_dolboorum(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    return render(request, "regproje/register/menin_dolboorum.html")

def dolboor_list(request):
    dolboor_list = Dolboor.objects.filter(user=request.user)
    if not dolboor_list:
        return redirect('regproje:dolboor_create')
    return render(request, "regproje/register/reg-2.html", {'dolboor_list': dolboor_list})

def dolboor_create(request):
    if request.method == 'POST':
        form = DolboorForm(request.POST)
        if form.is_valid():
            dolboor = form.save(commit=False)
            dolboor.user = request.user
            dolboor.save()
            return redirect('regproje:dolboor_list')
    else:
        form = DolboorForm()
    return render(request, "regproje/register/reg-2.html", {'form': form})

def dolboor_edit(request, pk):
    dolboor = get_object_or_404(Dolboor, pk=pk)
    if request.method == 'POST':
        form = DolboorForm(request.POST, instance=dolboor)
        if form.is_valid():
            form.save()
            return redirect('regproje:dolboor_list')
    else:
        form = DolboorForm(instance=dolboor)
    return render(request, "regproje/register/reg-2.html", {'form': form, 'dolboor': dolboor})

def dolboor_delete(request, pk):
    dolboor = get_object_or_404(Dolboor, pk=pk)
    if request.method == 'POST':
        dolboor.delete()
        return redirect('regproje:dolboor_list')
    return render(request, "regproje/register/dolboor_confirm_delete.html", {'dolboor': dolboor})

# negizgimaalimat basi
def negizgimaalymat_list(request):

    negizgimaalymat_list = Negizgimaalymat.objects.filter(user=request.user)

    if not negizgimaalymat_list:  # Eğer queryset boşsa
        return redirect('regproje:negizgimaalymat_create')
    return render(request, 'regproje/register/reg-1.html', {'negizgimaalymat_list': negizgimaalymat_list})

def negizgimaalymat_create(request):
    if request.method == 'POST':
        form = NegizgimaalymatForm(request.POST)
        if form.is_valid():
            negizgimaalymat = form.save(commit=False)
            negizgimaalymat.user = request.user
            negizgimaalymat.save()
            return redirect('regproje:negizgimaalymat_list')
    else:
        form = NegizgimaalymatForm()
    return render(request, 'regproje/register/reg-1.html', {'form': form})


def negizgimaalymat_edit(request, pk):
    negizgimaalymat = get_object_or_404(Negizgimaalymat, pk=pk)
    if request.method == 'POST':
        form = NegizgimaalymatForm(request.POST, instance=negizgimaalymat)
        if form.is_valid():
            form.save()
            return redirect('regproje:negizgimaalymat_list')
    else:
        form = NegizgimaalymatForm(instance=negizgimaalymat)
    return render(request, 'regproje/register/reg-1.html', {'form': form})

def negizgimaalymat_delete(request, pk):
    negizgimaalymat = get_object_or_404(Negizgimaalymat, pk=pk)
    if request.method == 'POST':
        negizgimaalymat.delete()
        return redirect('regproje:negizgimaalymat_list')
    return render(request, 'regproje/register/negizgimaalymat_confirm_delete.html', {'negizgimaalymat': negizgimaalymat})
# negizgimaalimat buttu

def kenenmaalymat_list(request):
    kenenmaalymat_list = Kenenmaalymat.objects.filter(user=request.user)
    if not kenenmaalymat_list:
        return redirect('regproje:kenenmaalymat_create')
    return render(request, "regproje/register/kenenmaalymat.html", {'kenenmaalymat_list': kenenmaalymat_list})

def kenenmaalymat_create(request):
    if request.method == 'POST':
        form = KenenmaalymatForm(request.POST)
        if form.is_valid():
            kenenmaalymat = form.save(commit=False)
            kenenmaalymat.user = request.user
            kenenmaalymat.save()
            return redirect('regproje:kenenmaalymat_list')
    else:
        form = KenenmaalymatForm()
    return render(request, "regproje/register/kenenmaalymat.html", {'form': form})

def kenenmaalymat_edit(request, pk):
    kenenmaalymat = get_object_or_404(Kenenmaalymat, pk=pk)
    if request.method == 'POST':
        form = KenenmaalymatForm(request.POST, instance=kenenmaalymat)
        if form.is_valid():
            form.save()
            return redirect('regproje:kenenmaalymat_list')
    else:
        form = KenenmaalymatForm(instance=kenenmaalymat)
    return render(request, "regproje/register/kenenmaalymat.html", {'form': form, 'kenenmaalymat': kenenmaalymat})

def kenenmaalymat_delete(request, pk):
    kenenmaalymat = get_object_or_404(Kenenmaalymat, pk=pk)
    if request.method == 'POST':
        kenenmaalymat.delete()
        return redirect('regproje:kenenmaalymat_list')
    return render(request, "regproje/register/kenenmaalymat_confirm_delete.html", {'kenenmaalymat': kenenmaalymat})

def iskeashyruuplany_list(request):
    iskeashyruuplany_list = Iskeashyruuplany.objects.filter(user=request.user)
    if not iskeashyruuplany_list:
        return redirect('regproje:iskeashyruuplany_create')
    return render(request, "regproje/register/reg-3.html", {'iskeashyruuplany_list': iskeashyruuplany_list})

def iskeashyruuplany_create(request):
    if request.method == 'POST':
        form = IskeAshyruUplanyForm(request.POST)
        if form.is_valid():
            iskeashyruuplany = form.save(commit=False)
            iskeashyruuplany.user = request.user
            iskeashyruuplany.save()
            return redirect('regproje:iskeashyruuplany_list')
    else:
        form = IskeAshyruUplanyForm()
    return render(request, "regproje/register/reg-3.html", {'form': form})

def iskeashyruuplany_edit(request, pk):
    iskeashyruuplany = get_object_or_404(Iskeashyruuplany, pk=pk)
    if request.method == 'POST':
        form = IskeAshyruUplanyForm(request.POST, instance=iskeashyruuplany)
        if form.is_valid():
            form.save()
            return redirect('regproje:iskeashyruuplany_list')
    else:
        form = IskeAshyruUplanyForm(instance=iskeashyruuplany)
    return render(request, "regproje/register/reg-3.html", {'form': form, 'iskeashyruuplany': iskeashyruuplany})

def iskeashyruuplany_delete(request, pk):
    iskeashyruuplany = get_object_or_404(Iskeashyruuplany, pk=pk)
    if request.method == 'POST':
        iskeashyruuplany.delete()
        return redirect('regproje:iskeashyruuplany_list')
    return render(request, "regproje/register/iskeashyruuplany_confirm_delete.html", {'iskeashyruuplany': iskeashyruuplany})

def dolboordundudjeti_list(request):
    dolboordundudjeti_list = Dolboordundudjeti.objects.filter(user=request.user)
    if not dolboordundudjeti_list:
        return redirect('regproje:dolboordundudjeti_create')
    return render(request, "regproje/register/reg-4.html", {'dolboordundudjeti_list': dolboordundudjeti_list})

def dolboordundudjeti_create(request):
    if request.method == 'POST':
        form = DolboordundudjetiForm(request.POST)
        if form.is_valid():
            dolboordundudjeti = form.save(commit=False)
            dolboordundudjeti.user = request.user
            dolboordundudjeti.save()
            return redirect('regproje:dolboordundudjeti_list')
    else:
        form = DolboordundudjetiForm()
    return render(request, "regproje/register/reg-4.html", {'form': form})

def dolboordundudjeti_edit(request, pk):
    dolboordundudjeti = get_object_or_404(Dolboordundudjeti, pk=pk)
    if request.method == 'POST':
        form = DolboordundudjetiForm(request.POST, instance=dolboordundudjeti)
        if form.is_valid():

regproje/templates/regproje/partials/_menu_approvers.html
<ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:index' %}">
                <i class="bi bi-house-fill"></i>
                Башкы бет
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="">
                <i class="bi bi-archive"></i>
                 Долбоордун абалы
              </a>
            </li>
          </ul>
        </li>
</ul>

regproje/templates/regproje/partials/_menu_users.html
<ul class="nav flex-column">

            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:menin_dolboorum' %}">
                <i class="bi bi-archive"></i>
                 Долбоордун абалы
              </a>
            </li>
    <hr class="my-3"><li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-body-secondary text-uppercase " href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
              Форманы толтуруу
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="nav-item">
                <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:dolboor_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                1.Долбоор тууралуу маалымат
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:negizgimaalymat_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                2.Негизги маалымат
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:kenenmaalymat_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                3.Долбоор боюнча кенен маалымат
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:iskeashyruuplany_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                4.Ишке ашыруу планы
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:dolboordundudjeti_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                5.Долбоордун бюджети
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:dolboordunkomandasy_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                6.Долбоордун командасы
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:baaloo_turuktuuluk_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                7.Баалоо жана туруктуулук
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'regproje:tirkemeler_list' %}">
                <i class="bi bi-file-earmark-text"></i>
                8.Тиркемелер
              </a>
            </li>
          </ul>
        </li>
</ul>

regproje/templates/regproje/partials/_svg.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>